name: chatbot_project
description: A Flutter chatbot app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    